New structure
lavrpetrov/first_website pull request #7
Opened 2021-04-18 15:28 UTC by mustkov

Добавил наши страницы, отстилизовал, сделал файловую структуру(нужно обсудить с тобой как это делается правильно, в инете не нашел что-то). Мелкие исправления

2021-04-18 15:29 UTC, mustkov commented
Добавил бутстап, пока думаю норм, потом в планах перенести все на какой-то из нормальных фреймов. Сделаем это потом таском to do

2021-04-21 00:14 UTC, lavrpetrov requested changes
some .idea and .gitignore changes

2021-04-21 00:33 UTC, lavrpetrov commented
P.S. GitHub Pages failed to build your site.

2021-04-22 11:53 UTC, lavrpetrov approved these changes
Great!

2021-04-22 11:53 UTC, merged